### ISSUE TITLE
Create redirect page

### ISSUE THREAD

**Issue by 8itwerk** [PSU-CapstoneBrownHope/BrownHopeAidApp#113]
[ ] application received notification
[ ] retrieve application ID 
[ ] route request integration with backend / airtable

**Comment by mackfoggia** [comment]
This wiki article includes a basic idea of what information may be included in the redirect page, although disregard the human readable passphrases portion. https://github.com/PSU-CapstoneBrownHope/BrownHopeAidApp/wiki/User-Journey
