### ISSUE TITLE
Sign up route for backend

### ISSUE THREAD

**Issue by 8itwerk** [PSU-CapstoneBrownHope/BrownHopeAidApp#114]

**Comment by ShatteredFortress** [comment]
'Successfully' signs up a user, however currently being blocked by authorization issue: awaiting macks help to sort this last bit out

**Comment by ShatteredFortress** [comment]
Users can successfully log in and a record is created in both authorization, and user data tables, once a record is created, it updates the authorization table with the id of the user data record id
