### ISSUE TITLE
Change profile page according to the User Journey Demo wiki page

### ISSUE THREAD

**Issue by baloveless** [PSU-CapstoneBrownHope/BrownHopeAidApp#156]
- [x] Add text at the top of the page "If you have just created an account please allow up to 5 minutes for your info to show up in the system". This text should pop up conditional on whether we have the user data in the system. This requires changing the navigate from an empty response to output this message and only redirect to login if the user is not logged in.

**Comment by mackfoggia** [comment]
Ideally the backend will return a particular status if we are waiting for information, at which point a message like this would be displayed.

**Comment by baloveless** [comment]
> Ideally the backend will return a particular status if we are waiting for information, at which point a message like this would be displayed.

Okay that makes sense, it might not even need to be a backend thing with that idea. It could just be a message that pops up if the get info request returns empty fields. I agree it shouldn't be visible if they have user information popping up. It has the possibility to be confusing other wise.
