### ISSUE TITLE
Implement application status route

### ISSUE THREAD

**Issue by ShatteredFortress** [PSU-CapstoneBrownHope/BrownHopeAidApp#94]
- [x] Setup post request route to query Airtable for application status
- [x] Decide of valid date format from the frontend
- [x] add unit testing

**Comment by mackfoggia** [comment]
#146 offers a basic version of the route for the new model of name and date of birth (although it only checks name because dob isn't being sent by the frontend yet)

**Comment by ShatteredFortress** [comment]
added test for application status and added some sanity checks to the route so it doesnt hit the table with no first/last names
